name: Build and Publish

on:
  push:
    tags:
      - '*'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Nix
      uses: cachix/install-nix-action@v22
      with:
        extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"

    - name: Check
      shell: bash
      run: make nix-check

  build_and_publish:
    needs: check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Extract tag name
      shell: bash
      run: echo "IMAGE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      run: |
        docker build -f Containerfile -t ghcr.io/${{ github.repository }}/vellubot:${{ env.IMAGE_TAG }} .
        docker push ghcr.io/${{ github.repository }}/vellubot:${{ env.IMAGE_TAG }}
